### ISSUE TITLE
"TypeError: Path must be a string" after break from project

### ISSUE THREAD

**Issue by kingscott** [standard/standard-loader#64]
Encountered [this](https://github.com/webpack/webpack/issues/2463) issue, and resolved it by downgrading `node` to `v5.11.1` from `v6.0.0`. 

Took a week break from a project, then cloned, and did the regular steps but got this error:

``` bash
ERROR in ./src/app.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1429:5)
    at processText (/home/kingscott/newton/node_modules/standard/node_modules/eslint/lib/cli-engine.js:144:30)
    at CLIEngine.executeOnText (/home/kingscott/newton/node_modules/standard/node_modules/eslint/lib/cli-engine.js:671:26)
    at Linter.lintText (/home/kingscott/newton/node_modules/standard-engine/index.js:65:59)
    at Object.standardLoader (/home/kingscott/newton/node_modules/standard-loader/index.js:19:12)
 @ multi app
```

Turns out downgrading `node` was the solution. This is the [branch](https://github.com/kingscott/newton/tree/nasa-update) I am using. 

Thanks.

**Comment by kingscott** [comment]
Although the problem still persists with `node v6.0.0`, `standard v7.0.1` and `standard-loader v3.0.1`.

**Comment by ghinda** [comment]
@kingscott Can you try installing from my fork? The `standard` upgrade to `7.0.1` fixes it for me on node `6.1.0`.

`npm install https://github.com/ghinda/standard-loader.git#fix-string-path`

**Comment by kingscott** [comment]
Seems to be an error trying to install that URL. It works for me in browser. But `npm` cannot seem to find it.

**EDIT**: I had the wrong version of `node` selected. It does work, thanks! Just curious, what did you edit?

:+1:

**Comment by ghinda** [comment]
@kingscott Just updated `standard` to `7.0.1`. Here's the PR changeset:

https://github.com/timoxley/standard-loader/pull/65/files

**Comment by kingscott** [comment]
I was able to install `standard 7.0.1` and all is good. 

Thanks! @ghinda! 💯

**Comment by timoxley** [comment]
@kingscott I just released [standard-loader 4.0.0](https://github.com/timoxley/standard-loader/compare/3.0.0...4.0.0) which allows container app to specify which version of standard to use, please update and let me know if this works for you.

**Comment by kingscott** [comment]
@timoxley It's working for me!

**Comment by bookercodes** [comment]
You're awesome. Thank you for writing this in easy-to-search words.

**Comment by alex-shamshurin** [comment]
@alexbooker Yes, it helped.
