### ISSUE TITLE
Strange lint output

### ISSUE THREAD

**Issue by landed1** [standard/standard-loader#70]
Error is given as   Parsing error: Unexpected token =

  static propTypes = {
    definition: PropTypes.object.isRequired,
    typeDefinition: PropTypes.object.isRequired
  }

**Comment by saschagehlich** [comment]
Yup, same here - standard-loader seems to execute all the code before linting for some reason

Edit: I was wrong - @landed1: Your code is not ES6 compliant.

**Comment by timoxley** [comment]
> Your code is not ES6

👍

**Comment by timoxley** [comment]
Just need to configure standard to use the babel-eslint parser.

```js
  standard: {
    // config options to be passed through to standard e.g.
    parser: 'babel-eslint'
  }
```
