### ISSUE TITLE
Support ignoring files

### ISSUE THREAD

**Issue by dcalhoun** [standard/standard-loader#71]
[Defining an `ignore` property package](http://standardjs.com/index.html#how-do-i-ignore-files) does not appear to impact the files `standard-loader` lints. Would it be possible to add support for this or should I accomplish this a different way?

**Comment by kedoska** [comment]
@dcalhoun i'm using `"standard-loader": "^5.0.0"`

```json
  "standard": {
    "parser": "babel-eslint",
    "plugins": [],
    "ignore": [
      "/dist/",
      "webpack.config.js"
    ]
  }
```

it is working

**Comment by timoxley** [comment]
Thanks @kedoska. Please reopen if this isn't working for you @dcalhoun.

**Comment by dcalhoun** [comment]
Thanks for the information, @kedoska.

@timoxley yes, I am still struggling with this. (I cannot reopen the ticket, as I do not have privileges for this repository.) Both the files in my top-level `vendor` directory and the `googleAnalytics.js` file outside of the `vendor` directory are logging linting warnings in my `webpack-dev-server` log.

Below are the relevant configurations. If I need to share the entire files, just let me know. I can create a gist for that. Do you spot anything glaringly wrong?

```javascript
// webpack.config.js
// [...]
module: {
  { test: /\.js$/, loader: 'babel!standard', exclude: /node_modules/ }
}
// [...]
```

```javascript
// package.json
// [...]
"standard": {
  "globals": [
    "__APP__",
    "__DEV__",
    "__ENV__"
  ],
  "ignore": [
    "googleAnalytics.js"
  ]
}
// [...]
```

I can successfully suppress the linting warnings by adding them to the `exclude` pattern for the loader.

```javascript
{ test: /\.js$/, loader: 'babel!standard', exclude: /node_modules|vendor|googleAnalytics/ }
```

**Comment by kedoska** [comment]
@dcalhoun did you try with absolute OR relative paths just to verify that it is a problem related with the plugin? I'm not sure how `standard` excludes the directories/files.

```json
  "ignore": [
    "./googleAnalytics.js"
  ]
```

**Comment by dcalhoun** [comment]
@kedoska yes, I have tried all of the following for the specific `googleAnalytics.js `file. Even when using a global wildcard linting warnings show up in my server log.

```javascript
"ignore": [
  "./src/scripts/initializers/googleAnalytics.js",
  "/src/scripts/initializers/googleAnalytics.js",
  "src/scripts/initializers/googleAnalytics.js",
  "googleAnalytics.js",
  "googleAnalytics",
  "**/*.js"
  "**/*",
  "**",
  "*"
]
```

@timoxley I setup a [stripped down example repo](https://github.com/dcalhoun/standard-loader-test) of what I'm encountering.

**Comment by dcalhoun** [comment]
@timoxley will you please re-open this issue? I am still unable to get this working. I'll try to dive into the loader source soon.
