### ISSUE TITLE
Check .vue files

### ISSUE THREAD

**Issue by scriptPilot** [standard/standard-loader#74]
Hello everybody! Is there any way, to check `.vue` files?

Only the script path should be checked.

After load these files with [Vue Webpack loader](https://github.com/vuejs/vue-loader), the source code isn't standard anymore, so must be checked before.

Documentation: [Vue Single File Components](https://vuejs.org/v2/guide/single-file-components.html#ad)

Example code:
````
<template>
  <p>Some HTML Code</p>
</template>

<script>
  module.exports = {}
</script>
````

**Comment by timoxley** [comment]
Answer in https://github.com/feross/standard/issues/750

**Comment by timoxley** [comment]
👍
