### ISSUE TITLE
How can it stops the build process on "error"?

### ISSUE THREAD

**Issue by kedoska** [standard/standard-loader#75]
![screenshot from 2017-02-02 13-05-14](https://cloud.githubusercontent.com/assets/11739105/22561984/a2284d6e-e948-11e6-9e97-a8f62e7a60af.png)

having 

`"build": "yarn run test | webpack --config ./webpack.config.js -p"`

and this in webpack

```javascript
{
  enforce: 'pre',
  test: /\.js$/,
  loader: 'standard-loader',
  exclude: /(node_modules)/,
},
```

when standard fires an error, why it looks just like a Warning in Webpack?
How can it stops the build process?

**Comment by timoxley** [comment]
I've added an `"error": true` config to the loader. See [docs](https://github.com/timoxley/standard-loader#webpack-2). Setting this should do what you want.
