### ISSUE TITLE
update README example to use webpack 2

### ISSUE THREAD

**Issue by yaodingyd** [standard/standard-loader#76]
I know this is kind of a duplicated issue with #73, but it would be very helpful to folks new to webpack.

Also, configuring `standard` would also be changed into `options` in loaders.

Huge thanks to your work!

**Comment by timoxley** [comment]
@yaodingyd can you send a pull request?

**Comment by yaodingyd** [comment]
@timoxley Gladly!

**Comment by yaodingyd** [comment]
PR created #77.

Thanks!
