### ISSUE TITLE
TypeError when options is missing from rule

### ISSUE THREAD

**Issue by bdegreve** [standard/standard-loader#80]
standard-loader 6.0.0 fails hard when options is missing from webpack rule:

```
rules: [
      {
        enforce: 'pre',
        test: /\.jsx?$/,
        loader: 'standard-loader',
        exclude: /(node_modules|bower_components)/,
      },
      // other loaders...
    ]
```

This results in following error:
```
Module build failed: TypeError: Cannot set property 'filename' of null
    at Object.standardLoader (node_modules\standard-loader\index.js:13:19)
```

When there are no options, `loaderUtils.getOptions(this)` returns null, and setting filename on null won't work.

Also, return value of getOptions should be considered immutable according [webpack/loader-utils#56](https://github.com/webpack/loader-utils/issues/56):

> The returned options object is read-only, you should not modify it. This is because getOptions can not make assumptions on how to clone the object correctly.

**Comment by timoxley** [comment]
Thanks, good catch. Released in [6.0.1](https://github.com/timoxley/standard-loader/compare/6.0.0...6.0.1)

**Comment by chrisdothtml** [comment]
@timoxley Can you publish on npm? Thanks!

**Comment by timoxley** [comment]
Done

**Comment by bdegreve** [comment]
Thanks for the quick fix!
